### ISSUE TITLE
NullPointerException crash on Android when disconnecting

### ISSUE THREAD

**Issue by ivorcho** [opentok/opentok-react-native#284]
**Current behavior**
App hangs when unmounting the screen containing the `OTSession`, hence when the session is disconnecting.

**Steps to reproduce**
Have two parties in a video call. Unmount the `OTSession` component. It's not happening every single time.

**Example Project**
I am using `"opentok-react-native": "0.10.2"` & `opentok-android-sdk-2.16.0`.
Also I am using react-navigation for app navigation. The code below is a screen that is mounted and unmounted through react-navigation

```
export default class VideoChatRoomScreen extends Component {

  static navigationOptions = {
    header: null
  }

  constructor(props) {
    super(props)
    this.apiKey = '----'
    this.sessionId = '----'
    this.token = '----'

    this.state = {
      publishAudio: true,
      publishVideo: true,
      cameraPosition: 'front',
    }
  }

  componentDidMount() {
    KeepAwake.activate()
  }

  componentWillUnmount() {
    KeepAwake.deactivate()
  }

  leaveConversation = () => {
    this.props.navigation.goBack()
  }

  toggleAudio = () => {
    this.setState(prevState => ({
      publishAudio: !prevState.publishAudio,
    }))
  }

  toggleVideo = () => {
    this.setState(prevState => ({
      publishVideo: !prevState.publishVideo,
    }))
  }

  toggleCamera = () => {
    this.setState(prevState => ({
      cameraPosition: prevState.cameraPosition === 'front' ? 'back' : 'front',
    }))
  }

  render() {
    return (
      <View style={styles.container}>
        <OTSession
          apiKey={this.apiKey}
          sessionId={this.sessionId}
          token={this.token}
          options={{ useTextureViews: true }}>
          <OTSubscriber
            style={{
              width: '100%',
              height: '100%',
            }} />
          <OTPublisher
            style={{
              width: 100,
              height: 100,
              position: 'absolute',
              top: 35,
              left: 15,
            }}
            properties={this.state} />
        </OTSession>
        <TouchableOpacity
          style={styles.cameraBtn}
          onPress={this.toggleCamera}>
          <Icon
            name={'sync-alt'}
            size={20}
            color='white' />
        </TouchableOpacity>
        <View style={styles.actionsContainer}>
          <TouchableOpacity
            style={styles.micBtn}
            onPress={this.toggleAudio}>
            <Icon
              name={this.state.publishAudio ? 'microphone' : 'microphone-slash'}
              size={20}
              color='white' />
          </TouchableOpacity>
          <TouchableOpacity
            style={styles.closeBtn}
            onPress={this.leaveConversation}>
            <Icon
              name='phone'
              size={24}
              color='white' />
          </TouchableOpacity>
          <TouchableOpacity
            style={styles.videoBtn}
            onPress={this.toggleVideo}>
            <Icon
              name={this.state.publishVideo ? 'video' : 'video-slash'}
              size={20}
              color='white' />
          </TouchableOpacity>
        </View>
      </View>
    )
  }
}
```

**Relevant logs and/or screenshots**
```
    --------- beginning of crash
05-11 10:12:26.678 27772-27772/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: bg.consento.pro.staging, PID: 27772
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.opentok.android.Stream.getStreamId()' on a null object reference
        at com.opentokreactnative.OTSessionManager.onDisconnected(OTSessionManager.java:635)
        at com.opentok.android.SubscriberKit.onDisconnected(SubscriberKit.java:829)
        at com.opentok.android.SubscriberKit$2.onDisconnected(SubscriberKit.java:1005)
        at com.opentok.android.v3.Subscriber$3.run(Subscriber.java:412)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by waylon999** [comment]
I'm also seeing this issue since upgrading to version 0.10.2.

If I join a video call as the only participant, I can exit the call without issue. It only seems to be happening when there are two parties connected.

**Comment by msach22** [comment]
Thanks for pointing this out, I'll investigate this issue and update you folks on a resolution this week.

**Comment by msach22** [comment]
This fix has been released with v0.10.3

**Comment by og2t** [comment]
It doesn't seem to be fixed, the crash seems caused by the print log in `onDisconnected` function in `OTSessionManager.java` on line 639:
```javascript
printLogs("onDisconnected: Subscriber disconnected. Stream: "+subscriberKit.getStream().getStreamId());
```

Thanks!

**Comment by enricop89** [comment]
See https://github.com/opentok/opentok-react-native/issues/304#issuecomment-505342760

**Comment by palmas** [comment]
The promlem still exists( 
I'm also getting this error. In both 2.15.3 and in the latest 2.16.5 version.
OpenTok team, why do you close this issue when it is not fixed?

It is a very critical issue and we are thinking to stop using openTok and choose some other framework because of this...
